/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import desplazable.Desface;
import java.awt.BorderLayout;
import java.awt.EventQueue;

/**
 *
 * @author pc
 */
public class dashboardpanel extends javax.swing.JPanel {

   Desface desplace;
  
    public dashboardpanel() {
        initComponents();
        desplace = new Desface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radialGradientPanelRedondeado1 = new Vistas.elemetos.RadialGradientPanelRedondeado();
        jLabel1 = new javax.swing.JLabel();
        menuPlegable = new Vistas.elemetos.RadialGradientPanelRedondeado();
        lbl_proveedores = new javax.swing.JLabel();
        lbl_ventas = new javax.swing.JLabel();
        lbl_menuPlegable = new javax.swing.JLabel();
        lbl_facturas = new javax.swing.JLabel();
        lbl_carros = new javax.swing.JLabel();
        lbl_usuarios_y_empleados = new javax.swing.JLabel();
        lbl_citas = new javax.swing.JLabel();
        lbl_inicio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelContent = new Vistas.elemetos.RadialGradientPanelRedondeado();
        radialGradientPanelRedondeado6 = new Vistas.elemetos.RadialGradientPanelRedondeado();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout radialGradientPanelRedondeado1Layout = new javax.swing.GroupLayout(radialGradientPanelRedondeado1);
        radialGradientPanelRedondeado1.setLayout(radialGradientPanelRedondeado1Layout);
        radialGradientPanelRedondeado1Layout.setHorizontalGroup(
            radialGradientPanelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        radialGradientPanelRedondeado1Layout.setVerticalGroup(
            radialGradientPanelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(8, 23, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/logo_fixit_desktop.png"))); // NOI18N

        menuPlegable.setBackground(new java.awt.Color(8, 23, 46));

        lbl_proveedores.setBackground(new java.awt.Color(255, 255, 255));
        lbl_proveedores.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_proveedores.setForeground(new java.awt.Color(255, 255, 255));
        lbl_proveedores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ic_proveedores.png"))); // NOI18N
        lbl_proveedores.setText("Proveedores");
        lbl_proveedores.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_proveedores.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_proveedores.setIconTextGap(18);
        lbl_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_proveedoresMouseClicked(evt);
            }
        });

        lbl_ventas.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ventas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_ventas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ventas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ic_ventas.png"))); // NOI18N
        lbl_ventas.setText("Ventas");
        lbl_ventas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_ventas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_ventas.setIconTextGap(18);
        lbl_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ventasMouseClicked(evt);
            }
        });

        lbl_menuPlegable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_menuPlegable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ic_menu.png"))); // NOI18N
        lbl_menuPlegable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_menuPlegable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuPlegableMouseClicked(evt);
            }
        });

        lbl_facturas.setBackground(new java.awt.Color(255, 255, 255));
        lbl_facturas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_facturas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_facturas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ic_factura.png"))); // NOI18N
        lbl_facturas.setText("Facturación");
        lbl_facturas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_facturas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_facturas.setIconTextGap(18);
        lbl_facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_facturasMouseClicked(evt);
            }
        });

        lbl_carros.setBackground(new java.awt.Color(255, 255, 255));
        lbl_carros.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_carros.setForeground(new java.awt.Color(255, 255, 255));
        lbl_carros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_carros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ic_car.png"))); // NOI18N
        lbl_carros.setText("Carros");
        lbl_carros.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_carros.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_carros.setIconTextGap(18);
        lbl_carros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_carrosMouseClicked(evt);
            }
        });

        lbl_usuarios_y_empleados.setBackground(new java.awt.Color(255, 255, 255));
        lbl_usuarios_y_empleados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_usuarios_y_empleados.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuarios_y_empleados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_usuarios_y_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ic_usuarios_y_trabajadores.png"))); // NOI18N
        lbl_usuarios_y_empleados.setText("Usuarios");
        lbl_usuarios_y_empleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_usuarios_y_empleados.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_usuarios_y_empleados.setIconTextGap(18);
        lbl_usuarios_y_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_usuarios_y_empleadosMouseClicked(evt);
            }
        });

        lbl_citas.setBackground(new java.awt.Color(255, 255, 255));
        lbl_citas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_citas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_citas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_citas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ic_citas.png"))); // NOI18N
        lbl_citas.setText("Citas");
        lbl_citas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_citas.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_citas.setIconTextGap(18);
        lbl_citas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_citasMouseClicked(evt);
            }
        });

        lbl_inicio.setBackground(new java.awt.Color(255, 255, 255));
        lbl_inicio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_inicio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ic_inicio.png"))); // NOI18N
        lbl_inicio.setText("Inicio");
        lbl_inicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lbl_inicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lbl_inicio.setIconTextGap(18);
        lbl_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_inicioMouseClicked(evt);
            }
        });

        jButton1.setText("Change calendar mode");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPlegableLayout = new javax.swing.GroupLayout(menuPlegable);
        menuPlegable.setLayout(menuPlegableLayout);
        menuPlegableLayout.setHorizontalGroup(
            menuPlegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPlegableLayout.createSequentialGroup()
                .addGroup(menuPlegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_menuPlegable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_carros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_citas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_facturas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_proveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(lbl_ventas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_usuarios_y_empleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPlegableLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        menuPlegableLayout.setVerticalGroup(
            menuPlegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPlegableLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lbl_menuPlegable, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_carros, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_citas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_facturas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_usuarios_y_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContent.setBackground(new java.awt.Color(8, 23, 46));

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );

        radialGradientPanelRedondeado6.setBackground(new java.awt.Color(8, 23, 46));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/ic_perfil.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sesión iniciada como:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Admin");

        javax.swing.GroupLayout radialGradientPanelRedondeado6Layout = new javax.swing.GroupLayout(radialGradientPanelRedondeado6);
        radialGradientPanelRedondeado6.setLayout(radialGradientPanelRedondeado6Layout);
        radialGradientPanelRedondeado6Layout.setHorizontalGroup(
            radialGradientPanelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radialGradientPanelRedondeado6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(radialGradientPanelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(754, Short.MAX_VALUE))
        );
        radialGradientPanelRedondeado6Layout.setVerticalGroup(
            radialGradientPanelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radialGradientPanelRedondeado6Layout.createSequentialGroup()
                .addGroup(radialGradientPanelRedondeado6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(radialGradientPanelRedondeado6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, radialGradientPanelRedondeado6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(radialGradientPanelRedondeado6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuPlegable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radialGradientPanelRedondeado6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPlegable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_menuPlegableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuPlegableMouseClicked
      
         if (menuPlegable.getX() == 0) {
            desplace.desplazarIzquierda(menuPlegable, menuPlegable.getX(), -170, 10, 10);
        } else if (menuPlegable.getX() == -170) {
            desplace.desplazarDerecha(menuPlegable, menuPlegable.getX(), 0, 10, 10);
        }
    }//GEN-LAST:event_lbl_menuPlegableMouseClicked

    private void lbl_proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_proveedoresMouseClicked
        frmProveedor pr = new frmProveedor();
    pr.setSize(922, 703);
    pr.setLocation(0, 0);
    
    panelContent.removeAll();
    panelContent.add(pr, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_proveedoresMouseClicked

    private void lbl_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_inicioMouseClicked
        frmInicio in = new frmInicio();
    in.setSize(922, 703);
    in.setLocation(0, 0);
    
    panelContent.removeAll();
    panelContent.add(in, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    
    }//GEN-LAST:event_lbl_inicioMouseClicked

    private void lbl_carrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_carrosMouseClicked
        frmCarros cr = new frmCarros();
    cr.setSize(922, 703);
    cr.setLocation(0, 0);
    
    panelContent.removeAll();
    panelContent.add(cr, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_carrosMouseClicked

    private void lbl_citasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_citasMouseClicked
        frmCitas ct = new frmCitas();
    ct.setSize(922, 703);
    ct.setLocation(0, 0);
    
    panelContent.removeAll();
    panelContent.add(ct, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_citasMouseClicked

    private void lbl_facturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_facturasMouseClicked
    frmFacturacion fr = new frmFacturacion();
    fr.setSize(922, 703);
    fr.setLocation(0, 0);
    
    panelContent.removeAll();
    panelContent.add(fr, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_facturasMouseClicked

    private void lbl_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ventasMouseClicked
        frmVentas vt = new frmVentas();
    vt.setSize(922, 703);
    vt.setLocation(0, 0);
    
    panelContent.removeAll();
    panelContent.add(vt, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_ventasMouseClicked

    private void lbl_usuarios_y_empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usuarios_y_empleadosMouseClicked
        frmUsuarios us = new frmUsuarios();
    us.setSize(922, 703);
    us.setLocation(0, 0);
    
    panelContent.removeAll();
    panelContent.add(us, BorderLayout.CENTER);
    panelContent.revalidate();
    panelContent.repaint();
    }//GEN-LAST:event_lbl_usuarios_y_empleadosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!FlatLaf.isLafDark()) {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatDarculaLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        } else {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatIntelliJLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_carros;
    private javax.swing.JLabel lbl_citas;
    private javax.swing.JLabel lbl_facturas;
    private javax.swing.JLabel lbl_inicio;
    private javax.swing.JLabel lbl_menuPlegable;
    private javax.swing.JLabel lbl_proveedores;
    private javax.swing.JLabel lbl_usuarios_y_empleados;
    private javax.swing.JLabel lbl_ventas;
    private Vistas.elemetos.RadialGradientPanelRedondeado menuPlegable;
    private Vistas.elemetos.RadialGradientPanelRedondeado panelContent;
    private Vistas.elemetos.RadialGradientPanelRedondeado radialGradientPanelRedondeado1;
    private Vistas.elemetos.RadialGradientPanelRedondeado radialGradientPanelRedondeado6;
    // End of variables declaration//GEN-END:variables
}
