/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelo.Usuarios;
import Controlador.controlador;
import Modelo.Roles;

/**
 *
 * @author rdlfp
 */
public class frmRegistrarse extends javax.swing.JFrame {

   

    /**
     * Creates new form frmRegistrarse
     */
    public frmRegistrarse() {
        initComponents();
        this.setLocationRelativeTo(null);
    txtCorreoUser.setHint("correo"); // Establecer el hint al campo de correo

    }

    public static void initfrmRegistrarse(){
        Usuarios modelo = new Usuarios();
        frmRegistrarse vista = new frmRegistrarse();
        Roles mRoles = new Roles();
        controlador con = new controlador(modelo, vista, mRoles);
        vista.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radialGradientPanel1 = new Vistas.elemetos.RadialGradientPanel();
        btnAgregarUser = new Vistas.elemetos.Button();
        txtContra = new Vistas.elemetos.CustomTextField();
        cbComobox = new javax.swing.JComboBox<>();
<<<<<<< HEAD
        txtCorreoUser = new Vistas.elemetos.CustomTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
=======
        btnAgregarUser = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        button1 = new botones.button();
>>>>>>> fito

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(730, 659));

        radialGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarUser.setBackground(new java.awt.Color(255, 204, 0));
        btnAgregarUser.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarUser.setText("Siguiente");
        btnAgregarUser.setActionCommand("");
        btnAgregarUser.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        radialGradientPanel1.add(btnAgregarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 200, 50));

        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        radialGradientPanel1.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 350, 40));

        cbComobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        radialGradientPanel1.add(cbComobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 350, 30));

<<<<<<< HEAD
        txtCorreoUser.addActionListener(new java.awt.event.ActionListener() {
=======
        btnAgregarUser.setBackground(new java.awt.Color(77, 119, 236));
        btnAgregarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarUser.setText("Registrarme");
        btnAgregarUser.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> fito
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoUserActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        radialGradientPanel1.add(txtCorreoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 350, 40));
=======
        jPanel1.add(btnAgregarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 102, 40));
>>>>>>> fito

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrame ahora");
        jLabel1.setToolTipText("");
        radialGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/5 3.png"))); // NOI18N
        radialGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 480));

<<<<<<< HEAD
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/logoo-Photoroom 2.png"))); // NOI18N
        radialGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jLabel2.setText("Elige tu rol");
        radialGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 120, -1));

        getContentPane().add(radialGradientPanel1, java.awt.BorderLayout.CENTER);
=======
        button1.setBackground(new java.awt.Color(240, 202, 78));
        button1.setText("porque no sale");
        button1.setToolTipText("");
        button1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button1.setShadowColor(new java.awt.Color(240, 202, 78));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 130, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
>>>>>>> fito

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed


    private void txtCorreoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoUserActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initfrmRegistrarse();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    public Vistas.elemetos.Button btnAgregarUser;
    public javax.swing.JComboBox<String> cbComobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private Vistas.elemetos.RadialGradientPanel radialGradientPanel1;
    public Vistas.elemetos.CustomTextField txtContra;
    public Vistas.elemetos.CustomTextField txtCorreoUser;
=======
    public javax.swing.JButton btnAgregarUser;
    private botones.button button1;
    public javax.swing.JComboBox<String> cbComobox;
    public javax.swing.JLabel imgdecoracion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField txtContra;
    public javax.swing.JFormattedTextField txtCorreoUser;
>>>>>>> fito
    // End of variables declaration//GEN-END:variables
}
