
package Vistas;

import Controlador.controladorLogin;
import Modelo.Usuarios;

/**
 *
 * @author Estudiante
 */
public class Loginjava extends javax.swing.JFrame {

    /**
     * Creates new form Loginjava
     */
    public Loginjava() {
        initComponents();
        this.setLocationRelativeTo(this);
        txtContra.setHint("Contraseña");
        txtCorreo.setHint("Correo");

    }
    
    public static void initLogin(){
    Usuarios modelo=new Usuarios();
    Loginjava vista=new Loginjava();
        controladorLogin con=new controladorLogin(modelo, vista);
        
        vista.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radialGradientPanel1 = new Vistas.elemetos.RadialGradientPanel();
        btnLogin = new Vistas.elemetos.Button();
        txtContra = new Vistas.elemetos.CustomTextField();
        txtCorreo = new Vistas.elemetos.CustomTextField();
        btnOlvidecontra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radialGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(255, 204, 0));
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Iniciar sesión");
        btnLogin.setActionCommand("");
        btnLogin.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        radialGradientPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 200, 50));
        radialGradientPanel1.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 350, 40));
        radialGradientPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 350, 40));

        btnOlvidecontra.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        btnOlvidecontra.setForeground(new java.awt.Color(255, 255, 255));
        btnOlvidecontra.setText("¿Olvidaste la contraseña?");
        radialGradientPanel1.add(btnOlvidecontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/5 3.png"))); // NOI18N
        radialGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio de sesión");
        jLabel1.setToolTipText("");
        radialGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/logoo-Photoroom 2.png"))); // NOI18N
        radialGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radialGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radialGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initLogin();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Vistas.elemetos.Button btnLogin;
    public javax.swing.JLabel btnOlvidecontra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private Vistas.elemetos.RadialGradientPanel radialGradientPanel1;
    public Vistas.elemetos.CustomTextField txtContra;
    public Vistas.elemetos.CustomTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
