/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author Jaimew
 */
public class RegisterNuevo extends javax.swing.JPanel {

    /**
     * Creates new form RegisterNuevo
     */
    public RegisterNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radialGradientPanelRedondeado1 = new Vistas.elemetos.RadialGradientPanelRedondeado();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout radialGradientPanelRedondeado1Layout = new javax.swing.GroupLayout(radialGradientPanelRedondeado1);
        radialGradientPanelRedondeado1.setLayout(radialGradientPanelRedondeado1Layout);
        radialGradientPanelRedondeado1Layout.setHorizontalGroup(
            radialGradientPanelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
        );
        radialGradientPanelRedondeado1Layout.setVerticalGroup(
            radialGradientPanelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(radialGradientPanelRedondeado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 671, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/Diseño sin título (5).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private Vistas.elemetos.RadialGradientPanelRedondeado radialGradientPanelRedondeado1;
    // End of variables declaration//GEN-END:variables
}
